<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Soda Ventures Away</title>
        <link rel="stylesheet" href="assets/style.css">
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Darumadrop+One&family=Rubik+Burned&display=swap" rel="stylesheet">
    </head>
    <body>

    </body>
</html>

<?php
require "partials/_header.phtml";
require "partials/_main.phtml";
require "partials/_footer.phtml";
?>